
-- | This module has the translation tables for the genetic code.

module Biobase.Codon where

import qualified Data.Map.Strict as M

codonTable = M.fromList
  [ ("aaa",'K')
  , ("aac",'N')
  , ("aag",'K')
  , ("aat",'N')
  , ("aca",'T')
  , ("acc",'T')
  , ("acg",'T')
  , ("act",'T')
  , ("aga",'R')
  , ("agc",'S')
  , ("agg",'R')
  , ("agt",'S')
  , ("ata",'I')
  , ("atc",'I')
  , ("atg",'M')
  , ("att",'I')
  , ("caa",'Q')
  , ("cac",'H')
  , ("cag",'Q')
  , ("cat",'H')
  , ("cca",'P')
  , ("ccc",'P')
  , ("ccg",'P')
  , ("cct",'P')
  , ("cga",'R')
  , ("cgc",'R')
  , ("cgg",'R')
  , ("cgt",'R')
  , ("cta",'L')
  , ("ctc",'L')
  , ("ctg",'L')
  , ("ctt",'L')
  , ("gaa",'E')
  , ("gac",'D')
  , ("gag",'E')
  , ("gat",'D')
  , ("gca",'A')
  , ("gcc",'A')
  , ("gcg",'A')
  , ("gct",'A')
  , ("gga",'G')
  , ("ggc",'G')
  , ("ggg",'G')
  , ("ggt",'G')
  , ("gta",'V')
  , ("gtc",'V')
  , ("gtg",'V')
  , ("gtt",'V')
  , ("taa",'/')
  , ("tac",'Y')
  , ("tag",'/')
  , ("tat",'Y')
  , ("tca",'S')
  , ("tcc",'S')
  , ("tcg",'S')
  , ("tct",'S')
  , ("tga",'/')
  , ("tgc",'C')
  , ("tgg",'W')
  , ("tgt",'C')
  , ("tta",'L')
  , ("ttc",'F')
  , ("ttg",'L')
  , ("ttt",'F')
  ]
